### ISSUE TITLE
Mention whether Buffer actually inherits Uint8Array like it does on Node.js

### ISSUE THREAD

**Issue by kenchris** [01org/iot-js-api#11]
That is pretty essential as that is part of JS itself today and what the web platform uses

**Comment by zolkis** [comment]
The text says
> Buffer is a [node.js API](https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html)

that is, it is already clear about this.

**Comment by kenchris** [comment]
I disagree... so this should mean that inheriting from Uint8Array is not supported? Why not just make it more clear

**Comment by zolkis** [comment]
Buffer is *the* node.js Buffer API. I don't need to repeat text from its spec, just tell the differences.

**Comment by kenchris** [comment]
So it does inherit or not? If it is the node.js Buffer API, then it should inherit.

**Comment by zolkis** [comment]
The [`Buffer` documentation](https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html) says:

> Buffer instances are also Uint8Array instances. However, there are subtle incompatibilities with the TypedArray specification in ECMAScript 2015. For example, while ArrayBuffer#slice() creates a copy of the slice, the implementation of Buffer#slice() creates a view over the existing Buffer without copying, making Buffer#slice() far more efficient.

I think that is clear and doesn't need any complementary mentions in the API spec.
