### ISSUE TITLE
Should gpio.close() be called gpio.release() instead?

### ISSUE THREAD

**Issue by kenchris** [01org/iot-js-api#13]
It seems more like an acquire/release pattern to me, which also fits with your comments in the code samples

**Comment by kenchris** [comment]
Could be board.gpio.acquire(...) as well

**Comment by zolkis** [comment]
open() and close() are consistent across different APIs, and clear about what they mean.

**Comment by kenchris** [comment]
but you don't use open in all places... ie board.gpio(...) (at least according to docs)
