### ISSUE TITLE
How to query on AIO what resolution is used (10 or 12 etc)

### ISSUE THREAD

**Issue by kenchris** [01org/iot-js-api#15]
SSIA

**Comment by zolkis** [comment]
That depends on what board is used, and that needs to be known by `require()`, so the resolution is known a priori from board documentation, no need for API. Of course it could be exposed, but why? Code doesn't need to be portable from board to board (and it's not, e.g. pin names are different etc).

**Comment by kenchris** [comment]
I am not sure it is always known and this would help porting code if I could just call a querying method

**Comment by zolkis** [comment]
Fixed in #10
