### ISSUE TITLE
The eventHandler "onupdaterequest" is undefined in Specification

### ISSUE THREAD

**Issue by wanghongjuan** [01org/iot-js-api#2]
The eventHandler `onupdaterequest` is undefined in whole OIC Specification except in the last example code, but I find it is exists in the `oic` when run command `var oic = require('iotivity-node')`. And I find the unit test [API Presence][] is using this eventHandler. Does the test case and example will remove this eventHandler, or add it to the Specification?

[API Presence]: https://github.com/otcshare/iotivity-node/blob/master/tests/tests/API%20Presence/common-server.js#L27

**Comment by gabrielschulhof** [comment]
@zolkis I think you need to update ```(.*)updaterequest``` to ```\1changerequest```.

**Comment by zolkis** [comment]
Fixed by #5 . Please check and close the issue if resolved.

**Comment by wanghongjuan** [comment]
It seems that this eventHandler was removed from #5. @gabrielschulhof Does the test cases will remove it  too?

**Comment by zolkis** [comment]
It is called [`update` event](https://github.com/01org/iot-js-api-test-suite/blob/master/api/ocf/server.md#onupdate) on the Server API.
