### ISSUE TITLE
"resource.resourcePath" is no equal to "request.target" in "onretrieve/onupdate/ondelete" method

### ISSUE THREAD

**Issue by wanghongjuan** [01org/iot-js-api#29]
According to [specification](https://github.com/01org/iot-js-api/blob/master/api/ocf/server.md), describe the [`onretrieve`](https://github.com/01org/iot-js-api/blob/master/api/ocf/server.md#onretrieve) method as below:
```
Find the ServerResource object resource for which resource.resourcePath is equal to request.target
```
The `resource.resourcePath` is a property of dictionary `ResourceId`, however `request.target` return `ResourceId `. It is obvious that they are not equal.

The [`onupdate`](https://github.com/01org/iot-js-api/blob/master/api/ocf/server.md#the-onupdatehandler-method) method and [`ondelete`](https://github.com/01org/iot-js-api/blob/master/api/ocf/server.md#the-ondeletehandler-method) method has same error as `onretrieve` method. The correct content should be `Find the ServerResource object resource for which resource.resourcePath is equal to request.target.resourcePath`. I think maybe they are typos, since the `oncreate` method is right.

**Comment by gabrielschulhof** [comment]
These bugs should all be filed against iotivity-node, not iot-js-api.

**Comment by wanghongjuan** [comment]
Hi, @gabrielschulhof  Actually, the `resource.resourcePath` is equal to `request.target.resourcePath`and `resource` is equal to `request.target`  in implementation, in other words, the `resource.resourcePath` is no equal to `request.target` in "onretrieve/onupdate/ondelete" method. But the spec description is reverse. If you think the `resource.resourcePath` should be equal to `request.target` in "onretrieve/onupdate/ondelete" method, I will file this issue to iotivity-node.

**Comment by zolkis** [comment]
Right, I needed to fix the wording in the spec. Thanks for spotting out!

**Comment by wanghongjuan** [comment]
@zolkis Thanks, I noticed that the `onretrieve` method has been updated in the fixed PR, what about the `onupdate` and `ondelete` method?

**Comment by zolkis** [comment]
Yes. Now they are fixed as well.

**Comment by wanghongjuan** [comment]
Thanks for quickly response. :)
