### ISSUE TITLE
The created interface "OicResource" by "findResources()" doesn't match with Specification

### ISSUE THREAD

**Issue by wanghongjuan** [01org/iot-js-api#3]
As the specification, `The OicResource objects can be created only by findResources()`, so we can get all properties of `OicResources` and they are defined. Actually, the object is different with the specification by running below code:
#### Step to reproduce

server.js

```
var oic = require( "../../../index" )( "server" ),
oic.register( {
    id: { path: "/a/" + uuid },
    resourceTypes: [ "core.light" ],
    mediaTypes: [ "mp4" ],
    interfaces: [ "oic.if.baseline" ],
    discoverable: true,
    observable: false,
    properties: { count: 0 },
    slow: false,
    links: [ "/a/" ]
} ).then(
...
```

Then get the interface `OicResource` via method `findResources()` on client and show it detail information:

```
{
  "active": false,
  "discoverable": true,
  "id": {
    "deviceId": "38306436-6531-3139-2d65-3731372d3464",
    "path": "/a/9c3dbe26-7125-4acd-9406-c69cb68507ec"
  },
  "interfaces": [
    "oic.if.baseline"
  ],
  "observable": false,
  "properties": {},
  "resourceTypes": [
    "core.light"
  ],
  "secure": false,
  "slow": false
}
```

We can see the properties `active` and `secure` of interface `OicResource` are undefined in specification, and the properties `mediaTypes`, `links` and the eventHandler `ondelete` are defined in specification, but they are undefined in implement. The question is coming, which standard that we should to following?
BTW, Is there any relationship between method `findResources()` and `register()`?
#### Board information

Target platform and image: Edison and Ostro [image#473](https://download.ostroproject.org/builds/ostro-os/2016-07-04_12-17-07-build-473/images/edison/ostro-image-swupd-dev-edison-2016-07-04_12-17-07-build-473.toflash.tar.bz2%29)

**Comment by wanghongjuan** [comment]
The spec defined property `resourceTypes` is a `sequence<DOMString>`(String), actually, get the type is `object`, the property `interfaces` has same situation as `resourceTypes`. And spec defined the property "links" is object. I set a wrong value `true` to property `links`, and it works well, it seems that the property value will not to be checked.

**Comment by gabrielschulhof** [comment]
I'm not sure what ```sequence<DOMString>``` is, but I assume it's an **array** of strings. As such, in Javascript, ```typeof []``` returns ```object``` no matter what type of object the array contains. So, ```object``` is correct AFAICT.

**Comment by zolkis** [comment]
In Web IDL a [sequence](https://www.w3.org/TR/WebIDL/#idl-sequence) is an array with value copy of the elements. The exact representation and implicit conversions are language specific. AFAIK in JavaScript, ```sequence<DOMString>``` translates to an array of [String values](http://www.ecma-international.org/ecma-262/6.0/#sec-terms-and-definitions-string-value) or [String objects](http://www.ecma-international.org/ecma-262/6.0/#sec-string-object).

**Comment by gabrielschulhof** [comment]
OK, so that means ```object``` is the correct result of ```typeof interfaces``` or ```typeof resourceTypes```.

**Comment by wanghongjuan** [comment]
OK, thanks for the detail information @zolkis .

**Comment by zolkis** [comment]
Fixed by #5 . Please check and close the issue if resolved.

**Comment by wanghongjuan** [comment]
Hi @zolkis , there are some difference between specification and implement. 

Property | Specification | Implement
------------ | ------------- | -------------
active | Undefined | Defined 
secure | Undefined | Defined
mediaTypes | Defined | Undefined
ondelete | Defined | Undefined

Following the #5 , the default value of `secure` is `true`, actually, get the value is `false`.

**Comment by wanghongjuan** [comment]
The content `The OicResource objects can be created only by findResources()` has been removed from updated spec, so I close this issue. Thanks.
