### ISSUE TITLE
OCF: Error types

### ISSUE THREAD

**Issue by wind-rider** [01org/iot-js-api#31]
The [OCF error types documentation](https://github.com/01org/iot-js-api/tree/master/api/ocf#ocferror) has an inconsistency:

There is an ```OcfPresenceError``` in
```The constructor of OcfDiscoveryError, OcfObserveError and OcfPresenceError takes the following parameters:```
but in the list above that, ```OcfPresenceError``` is not mentioned.

Was it renamed maybe?

iotivity-node seems [not to have all these error types](https://github.com/otcshare/iotivity-node/issues/120) and that's why I'm trying to find out what it should be.

**Comment by zolkis** [comment]
Presence has been removed from the OCF spec, so if there is a mention of `OcfPresenceError` in the spec (I have not found it), there is a bug in the spec :).

**Comment by zolkis** [comment]
OK, found it, will fix :) Thanks :)

**Comment by wind-rider** [comment]
Ok, nice :) then there is also this code in webidl.md, maybe it should also be removed:

```
    // Enable/disable presence for this device.
    enablePresence(optional unsigned long timeToLive): Promise<void>;  // in ms
    disablePresence(): Promise<void>;
```

**Comment by zolkis** [comment]
Fixed, closing.
