### ISSUE TITLE
Partial ClientResource dictionary

### ISSUE THREAD

**Issue by wind-rider** [01org/iot-js-api#32]
It is not very clear to me what a "partial ```ClientResource``` dictionary" is (used for the ```Promise``` returned with the ```update``` event in [```ClientResource```](https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#clientresource-events))

I thought ```Resource``` is the dictionary variant, and ```ClientResource``` has additional events and methods?

Besides it's not entirely clear to me how to model a "partial ClientResource dictionary" since it was defined before that most properties are not optional.

**Comment by zolkis** [comment]
It seems it should perhaps be more explicitly explained in the spec that partial means only the *changed* properties of the representation MUST be present. But as you have pointed out, it could always be a full representation. If you have an opinion on that, welcome.

**Comment by wind-rider** [comment]
I understand, but what I mean is that in the initial definition of Resource, most properties are not optional. When creating type definitions it is important to know when to mark something optional :)

**Comment by zolkis** [comment]
Fixed, please check if OK.
