### ISSUE TITLE
queryparam conveyance issue

### ISSUE THREAD

**Issue by WAvdBeek** [01org/iot-js-api#37]
queryparams are conveyed as an parameter variable on the request.
this is not possible with with the "if" queryparameter, since it clashes with if construct.
e.g. "if" it is an illegal variable name in javascript.

possible solution: prefix "_" the queryname for "if".

**Comment by zolkis** [comment]
I guess the issue refers to [this section](https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#retrieve) that says about the `options` parameter:

> The options argument is optional, and it is an object whose properties represent the REST query parameters passed along with the GET request as a JSON-serializable dictionary. Implementations SHOULD validate this client input to fit OCF requirements. The semantics of the parameters are application-specific (e.g. requesting a resource representation in metric or imperial units). Similarly, the properties of an OIC resource representation are application-specific and are represented as a JSON-serializable dictionary.

The `options` dictionary may have an `if` property, based on the OIC Core Spec. The claim seems to be that a dictionary cannot have a property like "if".

This is not true, &lt;anything&gt;**.if** does not clash with `if`, `options.if` is equivalent to `options["if"]` and the following code fragment works:
```javascript
var options = { mode: 1, if: [ "oic.if.a", "oic.if.r" ] };
console.log(options.if)
// VM376:1 ["oic.if.a", "oic.if.r"]

var opt = JSON.parse(JSON.stringify(options));
console.log(opt.if);
// VM520:1 ["oic.if.a", "oic.if.r"]
```
However, I would agree that the section is under-specified.

**Comment by gabrielschulhof** [comment]
You can also write
```JS
var something = { "if": "abc" };
```

**Comment by WAvdBeek** [comment]
e.g. the next code is ok:           
 var _units = "" ;  // string Units
            if (request.units != undefined ) {
                // possible values: ['C', 'F', 'K']
               _units = request.units ;
            }

this is not... how can I retrieve from request the contents of the query param if which I programmed as:
if (request.if != undefined ) {
               // possible values: ['oic.if.a', 'oic.if.s', 'oic.if.baseline'].
               _if = request.if;
            }

**Comment by gabrielschulhof** [comment]
TBH I don't understand the problem. The second snippet you wrote has no syntax errors in it. I tested it on node.js and zephyr.js with the following code:
```JS
var request = {};
if ( request.if != undefined ) {
  _if = request.if;
}
```
and neither of the runtimes complained. Nevertheless, if you feel uncomfortable writing `if` for any reason other than to start an if-statement, you can always write:
```JS
if ( request[ "if" ] != undefined ) {
  requestedInterfaces = request[ "if" ];
}
```
Could you please provide a more complete example of where this problem occurs? It may help me better understand the issue.

**Comment by zolkis** [comment]
Can we close this?
