### ISSUE TITLE
Discovery: findDevices/findResources/findPlatforms promise resolves to void not to the type of object it finds

### ISSUE THREAD

**Issue by gabrielschulhof** [01org/iot-js-api#7]
client.md says that the promise resolves to a ```Device``` resp. ```Resource``` resp. ```Platform```, but the WebIDL correctly states that
```
Promise<void> findResources(...);
Promise<void> findDevices(...);
Promise<void> findPlatforms(...);
```

**Comment by zolkis** [comment]
Right. I will fix this, the WebIDL is right. Follow that in the impl :).
